USE flask;

CREATE TABLE IF NOT EXISTS user(
    user_id INT UNSIGNED AUTO_INCREMENT,
    user_name VARCHAR(255) NOT NULL,
    user_passwd VARCHAR(255) NOT NULL,
    PRIMARY KEY(user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS device(
    device_id INT UNSIGNED AUTO_INCREMENT,
    device_uuid VARCHAR(37) NOT NULL,
    PRIMARY KEY(device_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS device_data(
    data_id INT UNSIGNED AUTO_INCREMENT,
    device_id INT UNSIGNED NOT NULL,
    data_time TIMESTAMP NOT NULL,
    rh FLOAT NOT NULL,
    tm FLOAT NOT NULL,
    lx FLOAT NOT NULL,
    dr FLOAT NOT NULL,
    PRIMARY KEY(data_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS device_event(
    event_id INT UNSIGNED AUTO_INCREMENT,
    event_time TIMESTAMP NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    device_id INT UNSIGNED NOT NULL,
    event_type INT UNSIGNED NOT NULL,
    event_ok TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY(event_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;